### ISSUE TITLE
snap.svg.zpd

### ISSUE THREAD

**Issue by huei90** [willianjusten/awesome-svg#104]
Hi @willianjusten I have a project in svg named `snap.svg.zpd`

I would like to add it to the list.
https://github.com/huei90/snap.svg.zpd

How do you think about this?

**Comment by willianjusten** [comment]
Great @huei90, you can add in [Libraries](https://github.com/willianjusten/awesome-svg/blob/master/topics/Libraries.md) topic =)

Just add and send me a PR.

**Comment by huei90** [comment]
done
https://github.com/willianjusten/awesome-svg/pull/108
